### ISSUE TITLE
NTR: agricultural household 

### ISSUE THREAD

**Issue by ramonawalls** [PopulationAndCommunityOntology/pco#25]
Term has been requested for the SDGIO ontology. Should be a subclass of household. Will need to create the terms for agricultural elsewhere, perhaps as a role in SDGIO.

**Comment by ramonawalls** [comment]
@ pbuttigieg @mark-jensen  Please let me know what you think will work best with the design patterns developing in SDGIO. I couldn't actually find "agricultural househould" referenced in any of the SDGs or targets.

Proposed possible definitions: 
1. A household in which the primary economic activity is agricultural.
2. A household in which the majority of the members are engaged in agricultural occupations
3. A household located in an agricultural area.

FYI, definition of household: A material entity that consists of one or more people who live in the same dwelling and also share at meals or living accommodation, and may consist of a single family or some other grouping of people.

**Comment by ramonawalls** [comment]
Added class http://purl.obolibrary.org/obo/PCO_0000028

**Comment by mark-jensen** [comment]
'agricultural household' appears in two indicators for Target 2.4

2.4.2: Percentage of agricultural households using irrigation systems compared to all agricultural households
2.4.3: Percentage of agricultural households using eco-friendly fertilizers compared to all agricultural households using fertilizers

Section IX from [this doc](http://www.fao.org/docrep/015/am085e/am085e.pdf) from FAO may be of help. In particular beginning on pg. 188, IX.4 on "Definition of the agricultural household-firm". It is from 2007 though.

> Proposed possible definitions: 
> 1. A household in which the primary economic activity is agricultural.
> 2. A household in which the majority of the members are engaged in agricultural occupations
> 3. A household located in an agricultural area.

3 will not work, for non-agricultural households exist in agricultural areas I believe.
2 is too narrow, since, from a quick look at the above doc, I take it that the common criteria for including a household in the "agricultural bin" is related to primary income source of least least one of its members. 

However, a look at the above indicators shows a more narrow criteria, that of a household engaged in agricultural practices on the same land as the household.

**Comment by mark-jensen** [comment]
@rlwalls2008 I don't see where 'agricultural household' was added.

PCO_0000028 has the label: 'community'

**Comment by ramonawalls** [comment]
Hmm. Looks like a Protege numbering problem. I may have overwritten
agricultural household when I added community. I will fix that and post
here when it is done.

**Comment by mark-jensen** [comment]
Any progress on drafting a definition?

If not, I'd suggest using a variation of # 1: "A household in which the majority of the income of its members is derived from agricultural activities."

This is the _narrow_ classification the above referenced doc refers to. The _broad_ classification is simply a household where any income is from agricultural sources. Although not prefect, it gives us something to work with in SDGIO. We can use it to elicit feedback from domain specialists.

**Comment by mark-jensen** [comment]
@rlwalls2008 Any chance to get a definition drafted soon? I could do a pull request using the above if that would help. SDGIO will need something in place quickly.

**Comment by ramonawalls** [comment]
@mark-jensen I used the definition you suggested. We don't have the terms to make a logical definition for this class at this point, but at least it has a text definition.
