### ISSUE TITLE
Move to BFO 2.0?

### ISSUE THREAD

**Issue by pbuttigieg** [PopulationAndCommunityOntology/pco#36]
Hi!

We're trying to import PCO, but it still uses [old BFO classes](https://github.com/PopulationAndCommunityOntology/pco/blob/master/src/ontology/ontology-metadata.owl#L5).
Would this be updated soon? Would be good to avoid building code to merge this with other imports.

**Comment by zhengj2007** [comment]
@rlwalls2008, If you'd like, I can work on it this weekend. We have developed an online tool for the BFO conversion.
http://ontobull.hegroup.org/bfoconvert

**Comment by ramonawalls** [comment]
Jie,

That would be really super! Yes, please! Are you zhengj2007?

Ramona

---

Ramona L. Walls, Ph.D.
Senior Scientific Analyst, CyVerse, University of Arizona
Research Associate, Bio5 Institute, University of Arizona

**Comment by zhengj2007** [comment]
@rlwalls2008 Yes, my account is zhengj2007. I will work on the conversion this weekend and let you know when I am done.

**Comment by ramonawalls** [comment]
Thank you! I just sent you an invitation to join the github organization.

Ramona

---

Ramona L. Walls, Ph.D.
Senior Scientific Analyst, CyVerse, University of Arizona
Research Associate, Bio5 Institute, University of Arizona

**Comment by zhengj2007** [comment]
I have accepted the invitation.

**Comment by zhengj2007** [comment]
I checked the development version PCO. It has been updated to BFO 2. I think that I have updated the files when I added 'household' in PCO. However, no release of PCO is made after changes. 

I found some minor issues and made following changes:
1). replace bfo import url:
    http://purl.obolibrary.org/obo/bfo.owl  
     by version IRI
    http://purl.obolibrary.org/obo/bfo/2014-05-03/classes-only.owl
since it is consistent with RO core.owl. Need to update it when RO core.owl updated

(This BFO classes only file has slight difference from the latest BFO 2.0 release. However, I will make some minor changes on BFO 2.0. So, would like to defer import this version BFO owl file.)

2). remove file: ro_imports.owl
    replace ontoFox imported RO relations by RO core file which URL is:
        http://purl.obolibrary.org/obo/ro/core.owl
    import RO core will show the deprecated BFO term 'obsolete dependent continuant'

The advantage of using RO core is that most of relations in the core file with defined domain and range which are very useful.
1. remove file: ontology-metadata.owl 
   since ontology-metadata.owl imported from URL, this file is not used
2. update pato_imports.owl
   replace google code link by github one in the file

After made these changes, I checked the PCO. It looks fine. All RO relations used in pco.owl are available in the RO core. Running Hermit reasoner, no inconsistent terms are found.

The changes I made can be viewed in the bfo2 branch:
https://github.com/PopulationAndCommunityOntology/pco/tree/bfo2/src/ontology

If no objection on the changes I made, I will merge bfo2 branch to the master and make a new release of PCO based on it. If anyone would like to review the files before I make the merge would be great.

In addition, I found the ontoFox input file for importing GO terms is same as PATO one. Need to find the ontoFox input file for GO terms.

**Comment by pbuttigieg** [comment]
Thanks Jie!

**Comment by zhengj2007** [comment]
@pbuttigieg Welcome!

@rlwalls2008 
PCO contains "taxonomic rank" and its subClasses which are not aligned with BFO. Do you want to keep them as they are now or move them under 'generically dependent continuant'? Would you like to review the PCO in bfo2 branch by this Friday? I am planning to merge the changes to the master branch and make a release file this weekend.

**Comment by ramonawalls** [comment]
@zhengj2007 Thanks for all the work! Sorry I didn't see your message sooner. I will review before Friday. Before the release, I need to add a bunch of new terms that have been requested. Should I just add those in the bfo2 branch? I can get them in by Friday, so you can work on the release over the weekend. I'll have a look at taxonomic rank too.

**Comment by zhengj2007** [comment]
@rlwalls2008 I think it would be nice to include the new terms in the release. If you review the BFO2 version is good, I'd prefer to merge it to the master branch before you add the new terms. Could you please let me know when you finish the review? Then I will merge the files to the master branch. I will let you know when I am done with it and make the release after you add the new terms. How do you think?

**Comment by ramonawalls** [comment]
Perfect, @zhengj2007. I will try to review today and let you know when I am done.

**Comment by zhengj2007** [comment]
@rlwalls2008 Thanks!

**Comment by ramonawalls** [comment]
@zhengj2007 Sorry tit took so long, but I just reviewed the branch, and it looks great. Please go ahead and merge. I will add new terms tomorrow and a few other things, so we can do a release. If you don't have time to do the merge before tomorrow, I can work on another branch.

**Comment by ramonawalls** [comment]
On further thought, @zhengj2007 ,  why don't I just merge the branch? As the repo owner, I should be able to do that. I'll let you know when it ready for the release.
