### ISSUE TITLE
Cede ENVO:alga to PCO

### ISSUE THREAD

**Issue by kaiiam** [PopulationAndCommunityOntology/pco#58]
ENVO: [alga](http://purl.obolibrary.org/obo/ENVO_02500019) should be ceded to PCO.

I intend to take care of this with the help of @pbuttigieg in the next several weeks, as part a pull request I wish to make to PCO, in which I would like to add a variety of classes concerning plankton communities and population growth processes.

Cheers,
Kai

**Comment by kaiiam** [comment]
Issue to be part of pull request pending permission [in issue 61](https://github.com/PopulationAndCommunityOntology/pco/issues/61)

**Comment by ramonawalls** [comment]
Replaces http://purl.obolibrary.org/obo/ENVO_02500019. No definition in ENVO.

Most definitions of algae exclude Cyanobacteria, so I think we should label this class 'alga excluding Cyanobacteria'.

Similar to `microbe`, this will be a subclass of `CARO:organism` (but not `organism, virus, or viroid`, since it includes only cellular organisms. It should also be a subclass of `NCBItaxon:cellular orgsnism`, which should be a subclass `of CARO:organism`, but I am concerned that if I mix up the CARO and NCBItaxon hierarchies, there will be problems with people importing PCO. Will wait for `CIB:organism` to be released.

Proposed definition: An organism that is part of a polyphyletic group of photosynthetic Eukaryotes excluding Embriophyta (land plants). Included organisms range from unicellular microalgae, such as Chlorella and diatoms, to multicellular forms, such as the giant kelp.
