### ISSUE TITLE
Autophagus ENVO-PCO-ENVO state?

### ISSUE THREAD

**Issue by pbuttigieg** [PopulationAndCommunityOntology/pco#59]
@ramonawalls (@cmungall)

It seems that there are a number of assertion in PCO around astronomical body, astronomical object, and a few other classes. 

This is causing AP duplication in ENVO. 
Why would there be assertions in PCO rather than clean imports? Or is this an ENVO artifact? Perhaps our makefile needs to be updated to reflect PCO's new, OSK-compliant structure (sans bridge file)?

![image](https://user-images.githubusercontent.com/2276146/31348872-471c2ed4-ad21-11e7-92df-f3b15bbc2741.png)

![image](https://user-images.githubusercontent.com/2276146/31348813-2bb2c18a-ad21-11e7-827f-c74bdff99e88.png)

**Comment by ramonawalls** [comment]
@pbuttigieg I certainly don't remember making any assertions in PCO about astronomical objects!

These classes are imported into PCO as part of the ENVO import. Then, when PCO is released, all of the import files are merged. I suspect that is what makes it look like the assertions are coming from PCO. I think this is standard practice, and I do like having the imports merged so people can work with the whole file without having to rely on imports.

Ideally, during the merge, PCO should maintain the fact that those assertions were made in ENVO, but I don't know how that works. Do you think it could be fixed in the ENVO make file, or do I need to make changes to PCO's production chain. 

This is an issue worth solving, because if it is on PCO's end, it is likely to happen in other cases of mutual import.

**Comment by ramonawalls** [comment]
I have added "is defined by" axioms to imported terms in PCO, but I don't know if it will solve this problem. Not sure what else I can do. I'm going to close this as "won't fix" but please re-open if there is something I can do to fix the problem.
