### ISSUE TITLE
NTR: taxon as collection of organisms

### ISSUE THREAD

**Issue by ramonawalls** [PopulationAndCommunityOntology/pco#88]
For new term requests, please provide the following information:

## Preferred term label

taxon as collection of organisms

## Synonyms

taxon

## Textual definition

A collection of organisms that has as members organisms of the same taxon. The taxon may be at any level. If the taxon is species, then this is the same as `species as a collection of organisms`. Membership in instances of this class will change with taxonomic revisions.

## Suggested parent term

collection of organisms

## Attribution

https://orcid.org/0000-0001-8815-0078

**Comment by ramonawalls** [comment]
Should add an xref to http://edamontology.org/data_1868

**Comment by cmungall** [comment]
(I will call this class by its acronym TACOO)

> A collection of organisms that has as members organisms of the same taxon

This isn't quite correct, otherwise the mereological sum consisting only of you+me would satisfy the definition. There needs to be some concept of maximality (see below on notes on time).

also: the definition *looks* circular, though in fact it's not as you are defining TACOO (taxon-sensu-collection) in terms of taxon-sensu-metaclass. But this poses the question, where does the definition of taxon-sensu-metaclass come from? And what does it mean to be 'of the same taxon'?

How does this related to @balhoff's taxrank ontology? http://obofoundry.org/ontology/taxrank

Jim, is your ontology an ontology of metaclasses (i.e whose instances are NCBITaxon classes?) or just tags?

> Membership in instances of this class will change with taxonomic revisions.

Perhaps rephrase as "members of instances of this class will change...".

But note this is a little problematic. On the one hand you may be saying that as we learn more we may revise member_of triples. But this is true of any instance graph. Reality does not change, just our representation. I think you mean something more. That for example the actual instance TACOO-Drosophila may grow and contract according to the whims of taxonomic societies of learned fly people. I don't think this sits well with the realist underpinnings of PCO and subclassing continuant. (I am the first to admit pragmatic limitations of realism, but I feel if you are going to commit to it, you should commit). Is continuant *really* what you want here, or is it an information entity (which can expand and contract with the whims of humans)?

Also: I believe in BFO as a collection is a continuant, this means that a membership of a TACOO also changes with time (but in a different way than above). The set of all members-of the instance  Human-TACOO-year-2020 has no members in with the instance Human-TACOO-year-1820. This is potentially confusing as one might expect TACOOs to be a 4D mereological ABox recapitulation of their cognate classes in NCBITaxon, but this is not in fact the case. 

I don't mind admitting metaclasses make my head hurt. I feel that trying to recapitulate metaclasses within a realist instance-based framework using mereology is fraught with problems. It may help to state some of the use cases and competency questions here.

**Comment by ramonawalls** [comment]
Thanks for the thoughtful feedback, @cmungall . Right about the definition. It should be defined similarly to `species as a collection of organisms` which is "A collection of organisms that has as parts every organism of given species and no organisms of any other species" with the comment "This term is neutral with respect to which organisms are included in a species. Membership will depend on the species concept and the taxonomic assertions used to define the species. These criteria must be specified by the user".

In this case, I am definitely looking for a continuant (the actual organisms) rather than an ICO, but I recognize the problems inherent in that.

@cmungall could you please point me at something or explain what you mean by metaclass?

In terms of changes over time as continuant, I think that is unavoidable, but my original choice of wording was poor. Whether or not an organisms is a member of an instance of a taxon should be consistent through time for any given taxon concept. So, membership in a TACOO won't change, but new taxon concepts will arise and old ones will go away. What is likely to change is who is a member of a "taxon" like _Drosophila melanogaster_, because people casually use species names without referring to the actual species concept. I think clearer wording can help with that problem. 

The primary use case here is to have an OBO-compatible class that is (as best as we can tell) equivalent to https://dwc.tdwg.org/terms/#taxon, which is "A group of organisms (sensu http://purl.obolibrary.org/obo/OBI_0100026) considered by taxonomists to form a homogeneous unit." [Note: Will need to update that organism reference in DwC as soon as the core ontology is ready.] Then in BCO modeling, we can more clearly define the `taxonomic identification process` which results in an organisms being declared a member of a taxon.

**Comment by ramonawalls** [comment]
@cmungall I see now that you were saying that a metaclass in this case means that instances of the class would be classes in NCBI.

**Comment by balhoff** [comment]
Taxrank was created by @pmidford. But my guess would be that the instances would be the classes in NCBI, so I guess that would make them metaclasses. They're just used as values for annotation properties on taxon classes.

**Comment by pmidford** [comment]
Yes, the terms were intended as metaclasses, but in practice, they would be used as annotation values, so what Jim said.

**Comment by ramonawalls** [comment]
Add an xref to http://purl.obolibrary.org/obo/GENO_0000113.

Alternative labels: taxonomic unit, taxonomic group

**Comment by ramonawalls** [comment]
I think we need stronger axioms than what taxrank provides, also these will be pre-composed with specific classes from NCBITaxon, but it would be good to include xrefs to taxrank.
